### PR TITLE
Migrating to go modules

### LINKED ISSUE #48: Migrating to Go modules
Are there any plans to migrating this project to using go modules?  

The reason I am requesting it is that it would make it easier to manage dependence when contributing.  Additionally since this package doesn't appear to be utilizing any other dependence manager migrating it to a single go module should be a simple change.

### PR DESCRIPTION
**Pull request by titusjaka**
What's done:
- migrated the project to go modules
- added config for [golangci-lint](https://github.com/golangci/golangci-lint) and migrated from gometalinter to golangci-lint

fixes #48

### CODE REVIEW

**Comment by titusjaka** [comment]
The build is still failing. I assume it's because of the secure variable `$FUZZIT_API_KEY` which is not available in PR.

**Comment by Ben-Ackerman** [comment]
Since this package already has multiple versions, I believe your module path in go.mod needs a version on the end /V2 or /V3 depending on if @jdkato wants to upgrade the major version as recommended in the link he added in issue #48 ?

**Comment by jdkato** [comment]
> The build is still failing. I assume it's because of the secure variable `$FUZZIT_API_KEY` which is not available in PR.

Yes, this is correct. This came up in the last PR, too, and I've been meaning to just disable fuzzing in PRs altogether.

Also, while I agree with the move to golangci-lint, I think it would be best if that change and any subsequent linting fixes were handled in a dedicated PR.

---
Back to the topic at hand, @Ben-Ackerman is correct: if we are to break any import paths, we'd need to bump the major version. 

In any case, I think we should discuss the plan more in #48 before any more work is done. The major considerations are how we handle the import paths (currently `gopkg.in/jdkato/prose.v2` and `github.com/jdkato/prose`) and the repository structure (currently `master` is v1 and `v2` is v2).

([`urfave/cli`](https://github.com/urfave/cli/issues/826) and [`go-yaml`](https://github.com/go-yaml/yaml) have both made similar transitions, which we may be able to learn from.)

**Comment by titusjaka** [comment]
Ok, I got it 😃 
So, I think it's better to close this PR and create a new one when you discuss versioning.

**Pull request closed without merging**
