### PR TITLE
Wrap location parsing in a function

### PR DESCRIPTION
**Pull request by jdkato**
This moves the logic that was in `chunk_test.go` into a new exported function named `Chunk`. The primary difference is that, instead of returning a slice of locations, we're now returning a slice of strings (i.e., the actual chunks).

This changes the usage from

```go
words := tokenize.TextToWords(text)
tagger := tag.NewPerceptronTagger()
tagged := tagger.Tag(words)
rs := Locate(tagged, TreebankNamedEntities)

for r, loc := range rs {
    res := ""
    for t, tt := range tagged[loc[0]:loc[1]] {
        if t != 0 {
            res += " "
        }
        res += tt.Text
    }

    if r >= len(expected) {
        t.Error("ERROR unexpected result: " + res)
    } else {
        if res != expected[r] {
            t.Error("ERROR", res, "!=", expected[r])
        }
    }
}
```

to

```go
words := tokenize.TextToWords(text)
tagger := tag.NewPerceptronTagger()
tagged := tagger.Tag(words)

for i, chunk := range Chunk(tagged, TreebankNamedEntities) {
    if i >= len(expected) {
        t.Error("ERROR unexpected result: " + chunk)
    } else {
        if chunk != expected[i] {
            t.Error("ERROR", chunk, "!=", expected[i])
        }
    }
}
```

/cc @elliott5

### CODE REVIEW

**Comment by elliott5** [comment]
Good work, but I need the Locate() func to be public, as I need the position to see where the chunks are for my application, so please could you make it public again.

I've also been doing some testing and discovered that the regexp is not quite right (as it includes leading adjectives). The one I am now using is:
```
// StrictTreebankNamedEntities matches proper names, excluding prior adjectives, possibly including numbers, and
// possibly including a linkage by preposition or subordinating conjunctions (for example "Bank of England").
var StrictTreebankNamedEntities = regexp.MustCompile(
	`((CD__)*(NNP.)+(CD__|NNP.)*)+` + // at least one proper noun, maybe preceded by an adjective and/or number
		`((IN__)*(CD__)*(NNP.)+(CD__|NNP.)*)*`) // then zero or more subordinated noun phrases
```

**Comment by jdkato** [comment]
I've made `Locate` public again. As far as the regexp, do you think I should replace `TreebankNamedEntities` or offer them both?

(Also, I need to stop coveralls from spamming PRs...)

**Comment by elliott5** [comment]
Yes @jdkato, as I'm probably the only person who uses it, I think it would be best to replace `TreebankNamedEntities`.

**Comment by jdkato** [comment]
Done!

**Pull request merged**
